routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::auth();

Route::get('/cron/reviews', 'CronController@getReviews');
Route::get('/cron/rate_reviews', 'CronController@rateReviews');
Route::get('/cron/daily', 'CronController@daily');

// Kiosk Mode
Route::get('/locations/{location}/reviewer', 'ReviewerController@createForLocation');
Route::post('/locations/{location}/reviewer', 'ReviewerController@storeForLocation');
Route::get('/locations/{location}/reviewer/success/{reviewer}', 'ReviewerController@successForLocation');
Route::get('/locations/{location}/write/{reviewer}', 'WriteReviewController@index');
Route::post('/locations/{location}/write/{reviewer}', 'WriteReviewController@store');
Route::get('/reviewer/{reviewer}/unsubscribe', 'ReviewerController@unsubscribe');

Route::get('/sms', 'CommunicationController@sms');

//for iframe
Route::get('/reviews/{location}/{user}', 'ReviewController@getLocationReviews')->name('getLocationReviews');

Route::group(['middleware' => 'auth'], function () {
	Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout');

    Route::post('/insights/search-competitors', 'InsightController@search');
    Route::post('/insights/save-competitor', 'InsightController@saveCompetitor');
    Route::get('/insights/competitors/{location}', 'InsightController@competitors')->name('competitors');
	Route::resource('/insights', 'InsightController');

	Route::get('/users/{user}/login', 'UserManagementController@supervise');
    Route::get('/users/create', 'UserManagementController@create')->name('users.create');
    Route::resource('/users', 'UserManagementController', ['except' => 'create']);

    Route::get('/team-members/{company}', 'TeamMemberController@index')->name('team-members.index');
    Route::get('/team-members/create/{company?}', 'TeamMemberController@create')->name('team-members.create');
    Route::get('/team-members/{companyUser}/edit', 'TeamMemberController@edit')->name('team-members.edit');
    Route::post('/team-members/{companyUser}', 'TeamMemberController@update')->name('team-members.update');
    Route::resource('/team-members', 'TeamMemberController', ['except' => 'index', 'create', 'edit', 'update']);

    //Route::resource('/permissions', 'PermissionController', ['only' => ['edit', 'update']]);
    Route::get('/permissions/{user}', 'PermissionController@edit')->name('permissions-edit');
    Route::post('/permissions/{user}', 'PermissionController@edit')->name('permissions-update');

	// Dashboard
	Route::get('/dashboard/location/{location}', 'DashboardController@setActiveLocation');
	Route::resource('/', 'DashboardController');
	Route::group(['middleware' => 'admin'], function () {
        Route::get('/super-dashboard', 'SuperDashboardController@index');
    });

    // Reviews
    Route::get('/reviews/reviews', 'ReviewController@getReviews');
	Route::post('/reviews/{review}/star', 'ReviewController@toggleStarred');

	Route::get('/reviews/{review}/{read}', 'ReviewController@show');
	Route::resource('/reviews', 'ReviewController');

	// Locations
    Route::get('/locations/{location}/reviews-widget', 'LocationController@reviewsWidget')->name('reviews-widget');
    //Route::put('/locations/{location}')
    Route::resource('/locations', 'LocationController');

    // Settings
	Route::get('/settings/primaryCard/{card}', 'SettingController@primaryCard');
	Route::post('/settings/saveCard', 'SettingController@saveCard');
	Route::resource('/settings', 'SettingController');

	// Reviews
	Route::get('/reviewers/import', 'ReviewerController@showImport');
	Route::get('/reviewers/{reviewer}/textForReview', 'ReviewerController@textForReview');
	Route::get('/reviewers/{reviewer}/emailForReview', 'ReviewerController@emailForReview');
	Route::get('/reviewers/{reviewer}/newCommunication', 'ReviewerController@newCommunication');
	Route::post('/reviewers/{reviewer}/communication', 'ReviewerController@sendCommunication');
	Route::post('/reviewers/import', 'ReviewerController@import');
	Route::resource('/reviewers', 'ReviewerController');

	// Sentiments
	Route::post('/sentiments/{category}/words', 'SentimentController@addWord');
	Route::put('/sentiments/{category}/words/{word}', 'SentimentController@editWord');
	Route::get('/sentiments/{category}/words/{word}/remove', 'SentimentController@deleteWord');
	Route::get('/sentiments/run', 'SentimentController@run');
	Route::resource('/sentiments', 'SentimentController');

	// Onboarding
	Route::get('/onboarding/search', 'OnboardingController@businessSearch');
	Route::get('/onboarding/coupon_lookup', 'OnboardingController@checkCoupon');
	Route::get('/onboarding/{step}', 'OnboardingController@showStep');
	Route::post('/onboarding/1', 'OnboardingController@saveInfo');
	Route::post('/onboarding/2', 'OnboardingController@addSource');
	Route::post('/onboarding/3', 'OnboardingController@saveCard');
	Route::post('/onboarding/4', 'OnboardingController@termsAccepted');
		
	// Sources
	Route::get('/locations/{location}/sources/fbpages', 'SourceController@getFbPages');
	Route::get('/locations/{location}/sources/googpages', 'SourceController@getGoogPages');
	Route::get('/locations/{location}/sources/yelpplaces', 'SourceController@getYelpPlaces');
	Route::get('/locations/{location}/sources/{source}/delete', 'SourceController@destory');
	Route::get('/oauth/googleredirect', 'SourceController@googleOauth');
    Route::post('/locations/store-media', 'LocationController@storeMedia');
    Route::resource('/locations/{location}/sources', 'SourceController');

    // Contact
    Route::post('/contact', 'ContactController@submit')->name('contact');

    //Notifications
    Route::get('/notifications', 'NotificationController@index')->name('notifications');

    //Potential leads
    Route::put('/leads/confirm', 'LeadController@confirm')->name('leads.confirm');
    Route::get('/leads/import', 'LeadController@import')->name('leads.import');
    Route::post('/leads/upload', 'LeadController@upload')->name('leads.upload');
    Route::get('/leads/check/{lead}', 'LeadController@check')->name('leads.check');
    Route::get('leads/{lead}/edit/{check?}', 'LeadController@edit')->name('leads.edit');
    Route::put('/leads/{lead}/{check?}', 'LeadController@update')->name('leads.update');
    Route::resource('/leads', 'LeadController', ['except' => ['edit', 'update']]);
    //Route::resource('/leads', 'LeadController');

    // Testing :)
    Route::get('/tests/getGoogle', 'TestController@getGoogle');
    Route::get('/tests/getFb', 'TestController@getFbReviews');

});

app/Models/Location.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\DB;

class Location extends Model{
     
    use SoftDeletes;
    
	function sources(){
		return $this->hasMany('App\Models\ReviewSourceUrl');
	}

	function reviews(){
		return $this->hasMany('App\Models\Review');
	}

	function reviewCounts(){
		return $this->hasMany('App\Models\ReviewCount');
	}

	function media(){
		return $this->hasMany('App\Models\LocationMedia');
	}

    function placeType()
    {
        return $this->belongsTo('App\Models\PlaceType', 'place_type');
    }

	function getAverageRatingAttribute(){
		$reviews = $this->reviews;
		$cnt = max(1, $reviews->count());
		return number_format($reviews->sum('rating') / $cnt * 5, 1);
	}

	function getAddressAttribute(){
		return $this->street . ", " . $this->city . ", " . $this->state . " " . $this->zip;
	}

	function getHashedIdAttribute(){
		return base64_encode($this->id * 12345);
	}

	function getMediaUrlAttribute(){
		$media = $this->media;
		$primary = $media->filter(function($m){
			return $m->is_primary;
		});

		if ($primary->count() > 0){
			return $primary->first()->url;
		}else if ($media->count() > 0){
			return $media->first()->url;
		}
		return NULL;
	}

	function getRatingAttribute(){
		$reviews = $this->reviews;
		if ($reviews->count() > 0){
	        return $reviews->sum('rating') / $reviews->count();
	    }else{
	        return 1;
	    }
	}

	static function findForHash($hash){
		$id = intval(base64_decode($hash) / 12345);
		return Location::find($id);
	}

}

app/Http/Controllers/LocationController.php
<?php

namespace App\Http\Controllers;

use App\Models\LocationMedia;
use App\Models\PlaceType;
use App\Models\TagType;
use Illuminate\Http\Request;

use Auth;
use App\Models\User;
use App\Models\Location;

class LocationController extends Controller{

    function index(){
    	$locations = Auth::user()->locations;
        return view('location.index', ['locations'=> $locations]);
    }

    function show($locationId){
    	$location = Location::find($locationId);
        $media = LocationMedia::where('location_id', $locationId)->get();
        $place_types = PlaceType::all();

        return view('location.show', [
    	    'location'=> $location,
            'media' => $media,
            'place_types' => $place_types,
        ]);
    }

    function create(){
    	return view('location.create');
    }

    function store(Request $request){
        $this->validate($request, [
            'location_name' => 'required',
            'places_id' => 'required_without:street,city,state,zip,country',
            'street' => 'required_without:places_id',
            'city' => 'required_without:places_id',
            'state' => 'required_without:places_id',
            'zip' => 'required_without:places_id',
            'country' => 'required_without:places_id',
        ]);

        $location = new Location;
        $location->text = $request->location_name;
        $location->street = $request->street;
        $location->city = $request->city;
        $location->state = isset($request->state) ? $request->state : '';
        $location->zip = isset($request->zip) ? $request->zip : '';
        $location->country = $request->country;
        $location->company_id = Auth::user()->companies->first()->id;
        $location->save();

        return redirect('/locations');
    }

    function storeMedia(Request $request)
    {
        $this->validate($request, [
            'location_id' => 'required|integer',
            'media_id' => 'required|integer',
        ]);

        $medias = LocationMedia::where('location_id', $request->location_id)->get();
        foreach ($medias as $media) {
            if($media->id != $request->media_id) {
                $media->is_primary = 0;
            } else {
                $media->is_primary = 1;
            }
            $media->save();
        }

        return response()->json('Saved', 200);
    }

    function reviewsWidget(int $location)
    {
        $location = Location::find($location)->hashed_id;
        return view('review.reviews-widget')
            ->with(['location' => $location]);
    }

    function update(Request $request, $location)
    {
        //dd($request->except(['_token', '_method']));
        $this->validate($request, [
            'text' => 'required|string',
            'street' => 'required|string',
            'city' => 'required|string',
            'state' => 'required|string',
            'zip' => 'required|string',
            'country' => 'required|string',
            'place_type' => 'required|int'
        ]);

        Location::where(['id' => $location])->update($request->except(['_token', '_method']));

        return redirect(route('locations.show', ['location' => $location]));
    }
    
}

resources/views/location/create.blade.php
@extends('layouts.dashboard')

@section('title')
    Add Location
@endsection

@section('content')
    <div class="row">
    	<div class="col-lg-9 col-md-12">
	    	<div class="card-box">
	        	<form class="form-horizontal" role="form" action="/locations" method="post" id="location-create-form">
	        		<input type="hidden" name="_token" value="{{ csrf_token() }}">
                    <input class="form-control hidden" name="places_id" type="hidden">

                    <div class="row">
                        <div id="company-img-container" class="col-12">
                            <div class="bg-icon bg-icon-primary onboarding-icon m-auto">
                                <img src="" class="hidden onboarding-icon-img" id='company-img'>
                            </div>
                        </div>
                        <div id="location-name-container" class="col-12">
                            <div class="form-group clearfix row m-t-10">
                                <label class="col-3 col-form-label" for="location_name">Location Name</label>
                                <div class="hidden col-9" id="location_text">
                                    <input class="form-control required" name="location_name" type="text" value="{{ old('text') }}">
                                </div>
                                <select class="form-control select2 find-location col-9 " name='yelp_id'></select>
                            </div>
                        </div>
                    </div>

                    <div id='location-detailed-information' class="hidden">

                        <div class="form-group row">
                            <label for="street" class="col-3 col-form-label">Street</label>
                            <div class="col-9">
                                <input class="form-control" name='street' value="{{ old('street') }}">
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="city" class="col-3 col-form-label">City</label>
                            <div class="col-9">
                                <input class="form-control" name='city' value="{{ old('city') }}">
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="state" class="col-3 col-form-label">State</label>
                            <div class="col-9">
                                <input class="form-control" name='state' value="{{ old('state') }}">
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="zip" class="col-3 col-form-label">Zip</label>
                            <div class="col-9">
                                <input class="form-control" name='zip' value="{{ old('zip') }}">
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="country" class="col-3 col-form-label">Country</label>
                            <div class="col-9">
                                <input class="form-control" name='country' value="{{  old('country') ?? 'USA' }}">
                            </div>
                        </div>
                    </div>

                    <div class="form-group m-b-0 row">
                        <div class="offset-3 col-9">
                            <button type="submit" class="btn btn-success">Add</button>
                        </div>
                    </div>

			    </form>
			</div>
		</div>
    </div>
    <!-- end row -->

@endsection

@push('scripts')
    <script src="{{ asset('js/find_location.js') }}"></script>
@endpush

resources/views/location/index.blade.php
@extends('layouts.dashboard')

@section('title')
    Locations
@endsection

@section('content')
    <div class="row">
        <div class="col-lg-12">
            <div class="card-box">
                <h4 class="text-dark  header-title m-t-0">All Locations
                	<div class="pull-right">
                		<a href="/locations/create" class="pull-right btn btn-success btn-sm" id="btn-archive">Add</a>
                	</div>
                </h4>
                <br>

                <table class="table mb-0 table-responsive">
                    <thead>
	                    <tr>
	                        <th>#</th>
	                        <th>Location Name</th>
	                        <th>Avg Rating</th>
	                    </tr>
                    </thead>
                    <tbody>
                    	@foreach($locations as $location)
		                    <tr>
		                        <td>{{ $location->id }}</td>
		                        <td><a href='/locations/{{ $location->id }}'>{{ $location->text }}</a></td>
		                        <td>{{ $location->average_rating }}</td>
		                    </tr>
		                @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <!-- end row -->

@endsection

resources/views/location/show.blade.php
@extends('layouts.dashboard')

@section('title')
    {{ $location->text }}
@endsection

@section('content')
    <div class="row">
        <div class="col-md-5">
            <div class="card-box">
                <h4 class="m-t-0 m-b-30 header-title">Location Information
                    <div class="pull-right">
                        <a href="{{ route('reviews-widget', ['location' => $location->id]) }}" class="btn btn-secondary waves-effect" style="padding: 4px 11px;"><i class="mdi mdi-comment-multiple-outline"></i> Get Reviews Widget</a>
                        @include('includes.kiosk-button', ['locations'=> collect([$location])])
                    </div>
                </h4>

                <form class="form-horizontal" role="form" action="{{ route('locations.update', ['location' => $location->id]) }}" method="post">
                    <input type="hidden" name="_token" value="{{ csrf_token() }}">
                    <input type="hidden" name="_method" value="PUT">

                    <div class="form-group row">
                        <label for="inputEmail3" class="col-3 col-form-label">Name</label>
                        <div class="col-9">
                            <input class="form-control" name='text' value='{{ $location->text }}'>
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="inputPassword3" class="col-3 col-form-label">Street</label>
                        <div class="col-9">
                            <input class="form-control" name='street' value='{{ $location->street }}'>
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="inputPassword4" class="col-3 col-form-label">City</label>
                        <div class="col-9">
                            <input class="form-control" name='city' value='{{ $location->city }}'>
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="inputPassword4" class="col-3 col-form-label">State</label>
                        <div class="col-9">
                            <input class="form-control" name='state' value='{{ $location->state }}'>
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="inputPassword4" class="col-3 col-form-label">ZIP</label>
                        <div class="col-9">
                            <input class="form-control" name='zip' value='{{ $location->zip }}'>
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="inputPassword4" class="col-3 col-form-label">Country</label>
                        <div class="col-9">
                            <input class="form-control" name='country' value='{{ $location->country ?? 'USA' }}'>
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="inputPassword4" class="col-3 col-form-label">Place Type</label>
                        <div class="col-9">
                            <select class="form-control select2" name="place_type" data-placeholder="Select Place Type">
                                <option>Select Place Type...</option>
                                @foreach ($place_types as $place_type)
                                    <option value="{{ $place_type->id }}" @if($place_type->id == $location->place_type) selected @endif>{{ $place_type->name }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>

                    <div class="form-group m-b-0 row">
                        <div class="offset-3 col-9">
                            <button type="submit" class="btn btn-info waves-effect waves-light">Update</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>

        <div class="col-md-7">
        	<div class="card-box">
                <h4 class="text-dark  header-title m-t-0">Review Sources
                	<div class="pull-right">
                		<a href="/locations/{{ $location->hashed_id }}/sources/create" class="pull-right btn btn-success btn-sm" id="btn-archive">Add</a>
                	</div>
                </h4>
                <br>

                <table class="table mb-0 table-responsive">
                    <thead>
	                    <tr>
	                        <th>#</th>
	                        <th>Type</th>
	                        <th>Link</th>
                            <th style="width: 20px;"></th>
	                    </tr>
                    </thead>
                    <tbody>
                    	@foreach($location->sources as $source)
		                    <tr>
		                        <td>{{ $source->id }}</td>
		                        <td><a href='/locations/{{ $location->id }}/sources/{{ $source->id }}'>{{ $source->type->text }}</a></td>
		                        <td><a href="{{ $source->url }}" target="_blank">link</a></td>
                                <td><a href="/locations/{{ $location->id }}/sources/{{ $source->id }}/delete"><i class="fa fa-trash"></i></a></td>
		                    </tr>
		                @endforeach

                    </tbody>
                </table>
            </div>

        </div>
    </div>
    <!-- end row -->

    <div class="row location-media">
        <div class="col-md-12">
            <div class="card-box">

            <div id="save-alert" class="d-none">
                <div class="alert alert-secondary alert-dismissible fade show" role="alert">
                    <strong>Saved</strong>
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            </div>

                <form method="POST" action="/locations/store-media">
                    <input type="hidden" name="_token" value="{{ csrf_token() }}">
                    <h4 class="text-dark header-title m-t-0 m-b-20">Location media
                        <div class="pull-right">
                            <button type="submit" class="pull-right btn btn-success btn-sm" id="btn-archive">Make primary</button>
                        </div>
                    </h4>

                    <div class="row">
                        @foreach($media as $img)
                            <div class="col text-center m-b-20 one-media">
                                <a href="javascript:void(0)"  data-location="{{ $location->id }}">
                                    <div class="checkbox checkbox-success checkbox-circle checkbox-single media-checkbox">
                                        <input type="checkbox" @if($img->is_primary) checked  @endif data-media="{{ $img->id }}">
                                        <label></label>
                                    </div>
                                    <img src="{{ $img->url }}" >
                                </a>
                            </div>
                        @endforeach
                    </div>
                </form>
            </div>
        </div>
    </div>

@endsection

@push('scripts')
    <script type="text/javascript">
        $(document).ready(function () {
            $('.one-media a').on('click', function(e) {
                if(!$(this).find('input[type="checkbox"]').is(':checked')) {
                    $(document).find('input[type="checkbox"]').attr('checked', false);
                    $(this).find('input[type="checkbox"]').attr('checked', 'checked');
                } else {
                    $(this).find('input[type="checkbox"]').attr('checked', false);
                }
            });

            $('.location-media form').submit(function (e) {
                e.preventDefault();

                var form = $(this);
                var data = {
                    'media_id' : form.find('input[type="checkbox"]:checked').data('media'),
                    'location_id' : form.find('a').data('location'),
                    '_token': "{{ csrf_token() }}"
                };

                $.ajax({
                    type: form.attr('method'),
                    url: form.attr('action'),
                    data: data,
                    success: function (response) {
                        $('#save-alert').removeClass('d-none').addClass('d-block');
                    },
                    error: function (response) {
                        console.log(response);
                    }
                });

            });
        });
    </script>
@endpush