routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::auth();

Route::get('/cron/reviews', 'CronController@getReviews');
Route::get('/cron/rate_reviews', 'CronController@rateReviews');
Route::get('/cron/daily', 'CronController@daily');

// Kiosk Mode
Route::get('/locations/{location}/reviewer', 'ReviewerController@createForLocation');
Route::post('/locations/{location}/reviewer', 'ReviewerController@storeForLocation');
Route::get('/locations/{location}/reviewer/success/{reviewer}', 'ReviewerController@successForLocation');
Route::get('/locations/{location}/write/{reviewer}', 'WriteReviewController@index');
Route::post('/locations/{location}/write/{reviewer}', 'WriteReviewController@store');
Route::get('/reviewer/{reviewer}/unsubscribe', 'ReviewerController@unsubscribe');

Route::get('/sms', 'CommunicationController@sms');

//for iframe
Route::get('/reviews/{location}/{user}', 'ReviewController@getLocationReviews')->name('getLocationReviews');

Route::group(['middleware' => 'auth'], function () {
	Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout');

    Route::post('/insights/search-competitors', 'InsightController@search');
    Route::post('/insights/save-competitor', 'InsightController@saveCompetitor');
    Route::get('/insights/competitors/{location}', 'InsightController@competitors')->name('competitors');
	Route::resource('/insights', 'InsightController');

	Route::get('/users/{user}/login', 'UserManagementController@supervise');
    Route::get('/users/create', 'UserManagementController@create')->name('users.create');
    Route::resource('/users', 'UserManagementController', ['except' => 'create']);

    Route::get('/team-members/{company}', 'TeamMemberController@index')->name('team-members.index');
    Route::get('/team-members/create/{company?}', 'TeamMemberController@create')->name('team-members.create');
    Route::get('/team-members/{companyUser}/edit', 'TeamMemberController@edit')->name('team-members.edit');
    Route::post('/team-members/{companyUser}', 'TeamMemberController@update')->name('team-members.update');
    Route::resource('/team-members', 'TeamMemberController', ['except' => 'index', 'create', 'edit', 'update']);

    //Route::resource('/permissions', 'PermissionController', ['only' => ['edit', 'update']]);
    Route::get('/permissions/{user}', 'PermissionController@edit')->name('permissions-edit');
    Route::post('/permissions/{user}', 'PermissionController@edit')->name('permissions-update');

	// Dashboard
	Route::get('/dashboard/location/{location}', 'DashboardController@setActiveLocation');
	Route::resource('/', 'DashboardController');
	Route::group(['middleware' => 'admin'], function () {
        Route::get('/super-dashboard', 'SuperDashboardController@index');
    });

    // Reviews
    Route::get('/reviews/reviews', 'ReviewController@getReviews');
	Route::post('/reviews/{review}/star', 'ReviewController@toggleStarred');

	Route::get('/reviews/{review}/{read}', 'ReviewController@show');
	Route::resource('/reviews', 'ReviewController');

	// Locations
    Route::get('/locations/{location}/reviews-widget', 'LocationController@reviewsWidget')->name('reviews-widget');
    //Route::put('/locations/{location}')
    Route::resource('/locations', 'LocationController');

    // Settings
	Route::get('/settings/primaryCard/{card}', 'SettingController@primaryCard');
	Route::post('/settings/saveCard', 'SettingController@saveCard');
	Route::resource('/settings', 'SettingController');

	// Reviews
	Route::get('/reviewers/import', 'ReviewerController@showImport');
	Route::get('/reviewers/{reviewer}/textForReview', 'ReviewerController@textForReview');
	Route::get('/reviewers/{reviewer}/emailForReview', 'ReviewerController@emailForReview');
	Route::get('/reviewers/{reviewer}/newCommunication', 'ReviewerController@newCommunication');
	Route::post('/reviewers/{reviewer}/communication', 'ReviewerController@sendCommunication');
	Route::post('/reviewers/import', 'ReviewerController@import');
	Route::resource('/reviewers', 'ReviewerController');

	// Sentiments
	Route::post('/sentiments/{category}/words', 'SentimentController@addWord');
	Route::put('/sentiments/{category}/words/{word}', 'SentimentController@editWord');
	Route::get('/sentiments/{category}/words/{word}/remove', 'SentimentController@deleteWord');
	Route::get('/sentiments/run', 'SentimentController@run');
	Route::resource('/sentiments', 'SentimentController');

	// Onboarding
	Route::get('/onboarding/search', 'OnboardingController@businessSearch');
	Route::get('/onboarding/coupon_lookup', 'OnboardingController@checkCoupon');
	Route::get('/onboarding/{step}', 'OnboardingController@showStep');
	Route::post('/onboarding/1', 'OnboardingController@saveInfo');
	Route::post('/onboarding/2', 'OnboardingController@addSource');
	Route::post('/onboarding/3', 'OnboardingController@saveCard');
	Route::post('/onboarding/4', 'OnboardingController@termsAccepted');
		
	// Sources
	Route::get('/locations/{location}/sources/fbpages', 'SourceController@getFbPages');
	Route::get('/locations/{location}/sources/googpages', 'SourceController@getGoogPages');
	Route::get('/locations/{location}/sources/yelpplaces', 'SourceController@getYelpPlaces');
	Route::get('/locations/{location}/sources/{source}/delete', 'SourceController@destory');
	Route::get('/oauth/googleredirect', 'SourceController@googleOauth');
    Route::post('/locations/store-media', 'LocationController@storeMedia');
    Route::resource('/locations/{location}/sources', 'SourceController');

    // Contact
    Route::post('/contact', 'ContactController@submit')->name('contact');

    //Notifications
    Route::get('/notifications', 'NotificationController@index')->name('notifications');

    //Potential leads
    Route::put('/leads/confirm', 'LeadController@confirm')->name('leads.confirm');
    Route::get('/leads/import', 'LeadController@import')->name('leads.import');
    Route::post('/leads/upload', 'LeadController@upload')->name('leads.upload');
    Route::get('/leads/check/{lead}', 'LeadController@check')->name('leads.check');
    Route::get('leads/{lead}/edit/{check?}', 'LeadController@edit')->name('leads.edit');
    Route::put('/leads/{lead}/{check?}', 'LeadController@update')->name('leads.update');
    Route::resource('/leads', 'LeadController', ['except' => ['edit', 'update']]);
    //Route::resource('/leads', 'LeadController');

    // Testing :)
    Route::get('/tests/getGoogle', 'TestController@getGoogle');
    Route::get('/tests/getFb', 'TestController@getFbReviews');

});

app/Models/Company.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;

class Company extends Model{
     
	protected $table='company';
    
	function locations(){
		return $this->hasMany('App\Models\Location');
	}

	function reviews()
    {
        return $this->hasMany('App\Models\Review');
    }

    function users()
    {
        return $this->belongsToMany('App\Models\User');
    }

	function getAddressAttribute(){
		return $this->locations->first()->address;
	}

	function reviewCounts(){
		return $this->hasMany('App\Models\ReviewCount');
	}

	function media(){
		return $this->hasMany('App\Models\LocationMedia');
	}

	function getMediaUrlAttribute(){
		$media = $this->media;
		$primary = $media->filter(function($m){
			return $m->is_primary;
		});

		if ($primary->count() > 0){
			return $primary->first()->url;
		}else if ($media->count() > 0){
			return $media->first()->url;
		}
		return NULL;
	}
}

app/Models/User.php
<?php

namespace App\Models;

use App\Notifications\PasswordReset;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    function companies(){
        return $this->belongsToMany('App\Models\Company');
    }

    function companyUser()
    {
        return $this->hasOne(CompanyUser::class);
    }

    function getLocationsAttribute(){
        $locations = $this->companies->load('locations')->map(function($c){
            return $c->locations;
        })->reduce(function ($carry, $item) {
            if ($carry != null){
                return $carry->merge($item);
            }
            return $item;
        });
        return $locations;
    }

    function getGravatarUrlAttribute(){
        return "https://www.gravatar.com/avatar/" . md5( strtolower( trim( $this->email ) ) ) . "&s=" . "100";
    }

    function createStripeCustomer(){
        if ($this->stripe_id == NULL){
            \Stripe\Stripe::setApiKey(env('STRIPE_SEC'));

            $customer = \Stripe\Customer::create([
                'email' => $this->email,
            ]);

            $this->stripe_id = $customer["id"];
            $this->save();
        }
    }

    public function sendPasswordResetNotification($token)
    {
        $this->notify(new PasswordReset($token));
    }

    function getHashedIdAttribute()
    {
        return base64_encode($this->id * 12345);
    }

    static function findByHash($hash)
    {
        $id = intval(base64_decode($hash) / 12345);
        return self::find($id);
    }

}

app/Http/Controllers/DashboardController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Auth;

use App\Models\User;
use App\Models\Company;
use App\Models\Location;
use App\Models\SentimentCategory;
use App\Models\ReviewCount;

use Carbon\Carbon;

class DashboardController extends Controller{

    function index(Request $request){
        if (Auth::user()->role_id == 1){
            return redirect('/super-dashboard');
        }

    	$company = Auth::user()->companies->first();
        if (empty($company)){
            return redirect('/onboarding/1');
        }
    	$categories = SentimentCategory::all();

        $activeLocationId = $request->cookie('active_location');
        $rating = 1;
        if ($activeLocationId != 0 && !empty($activeLocationId)){
            $location = Location::find($activeLocationId);
            $activeLocationId = $location->hashed_id;
            $reviews = $location->reviews->sortBy('native_created_at')->reverse();
            $counts = $location->reviewCounts()->where('created_at', '>', Carbon::now()->subDays(5))->get()->load('source');
            if ($reviews->count() > 0){
                $rating = $reviews->sum('rating') / $reviews->count();
            }else{
                $rating = 1;
            }
        }else{
            $reviews = $company->reviews->sortBy('native_created_at')->reverse();
            $counts = $company->reviewCounts()->where('created_at', '>', Carbon::now()->subDays(5))->get()->load('source');
            $location = NULL;
            if ($reviews->count() > 0){
                $rating = $reviews->sum('rating') / $reviews->count();
            }else{
                $rating = 1;
            }
        }

        // Get and format data for review count graphs, while zeroing out empty days
        $perSourcePerDay = array();
        $sourceIds = collect();
        if (!empty($counts->first())){
            $oldest = $counts->sortBy('created_at')->first()->created_at;
            $sourceIds = $counts->groupBy('review_source_id')->keys();

            foreach ($sourceIds as $sourceId) {
                $perSourcePerDay[$sourceId] = array();
            }

            for ($i = 0; $i <= $oldest->diffInDays(Carbon::now()); $i++){
                $day = $oldest->copy()->addDays($i)->format('m/d/y');
                $filtered = $counts->filter(function($c) use ($day){
                    return $c->created_at->format('m/d/y') == $day;
                });
                //dd($filtered);
                foreach ($sourceIds as $sourceId) {
                    $perSourcePerDay[$sourceId][$day] = $filtered->filter(function($c) use ($sourceId){
                        return $c->review_source_id == $sourceId;
                    })->values(); // Not using a groupBy here so that we get an empty collection if there are no objects
                }
            }
        } // END data formating

        return view('dashboard.index', [
            'company'=> $company,
            'reviews'=> $reviews,
            'categories'=> $categories,
            'perSourcePerDay'=>$perSourcePerDay,
            'sourceIds'=>$sourceIds,
            'location'=> $location,
            'rating'=> $rating,
            'active_location_id' => $activeLocationId,
        ]);
    }

    function setActiveLocation($locationId){
        $cookie = cookie('active_location', $locationId, 60*6);
        return redirect('/')->cookie($cookie);
    }
    
}

resources/views/dashboard/index.blade.php
@extends('layouts.dashboard')

@section('title')
    Dashboard
@endsection

@section('breadcrums')
    <div class="pull-right">
        <button type="button" class="btn btn-secondary dropdown-toggle waves-effect" data-toggle="dropdown" aria-expanded="false" style="padding: 4px 11px;">
            {{ $location->text ?? 'All Locations' }} <span class="caret"></span>
        </button>
        <div class="dropdown-menu" x-placement="bottom-start" style="position: absolute; transform: translate3d(0px, 38px, 0px); top: 0px; left: 0px; will-change: transform;">
            <a class="dropdown-item" href="/dashboard/location/0">All Locations</a>
            @foreach($company->locations as $l)
                <a class="dropdown-item" href="/dashboard/location/{{ $l->id }}">{{ $l->text }}</a>
            @endforeach
        </div>
    </div>
@endsection

@section('content')
    <div class="row">
        <div class="col-md-12">
            <div class="row">
                <div class="col-md-4">
                    <div class="card-box widget-bg-color-icon">
                        <div class="bg-icon bg-icon-primary" style="margin-left: auto; margin-right: auto;">
                            @if (empty($location))
                                <img style="height: 68px; border-radius: 35px; margin: auto;" src="{{ $company->media_url }}">
                            @else
                                <img style="height: 68px; border-radius: 35px; margin: auto;" src="{{ $location->media_url }}">
                            @endif
                        </div>
                        <h2 style="text-align: center; margin-top: 5px;"> {{ $location->text ?? $company->text }} </h2>
                        <p style="text-align: center;">{{ $location->address ?? $company->address }}</p>
                        <p style="text-align: center; font-size: 30px; margin-bottom: -7px;">
                            <i class="mdi mdi-star" style="color: {{ count($reviews) == 0 || $rating >= 0.2 ? 'gold' : 'grey' }};"></i>
                            <i class="mdi mdi-star" style="color: {{ count($reviews) == 0 || $rating >= 0.4 ? 'gold' : 'grey' }};"></i>
                            <i class="mdi mdi-star" style="color: {{ count($reviews) == 0 || $rating >= 0.6 ? 'gold' : 'grey' }};"></i>
                            <i class="mdi mdi-star" style="color: {{ count($reviews) == 0 || $rating >= 0.8 ? 'gold' : 'grey' }};"></i>
                            <i class="mdi mdi-star" style="color: {{ count($reviews) == 0 || $rating >= 1.0 ? 'gold' : 'grey' }};"></i>
                        </p>

                    </div>
                </div>

                <div class="col-md-8">
                    <div class="card-box" style="height: 244px; overflow: hidden;">
                        @if(count($reviews) > 0)
                            Number of Reviews
                            <div id="line-graph" class="ct-chart ct-golden-section" style="max-height: 200px;"></div>
                        @else
                            <div class="alert alert-danger">
                                <p>Be sure to get new reviews and keep this chart growing, up and to the right!</p>
                                <p>Click here to ask your customers for reviews.</p>
                                @if (empty($location))
                                    @include('includes.kiosk-button', ['locations'=> $company->locations])
                                @else
                                    @include('includes.kiosk-button', ['locations'=> collect([$location])])
                                @endif
                            </div>
                        @endif
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-9">
            <div class="card-box">
                <h4 class="m-t-0 m-b-20 header-title"><b>Reputation Monitor</b></h4>
                @if(count($reviews) > 0)
                    <div class="inbox-widget nicescroll" tabindex="5000" style="overflow: scroll; height: 700px;">
                        @include('review.reviews', ['reviews'=> $reviews])
                    </div>
                @else
                    <div class="alert alert-danger text-center">
                        <h4>No reviews yet?</h4>
                        <p>Connect your accounts to start populating reviews.</p>

                        @if($active_location_id)
                            <a href="/locations/{{ $active_location_id }}/sources/create" class="btn btn-secondary waves-effect text-left text-light">Connect Your Accounts</a>
                        @else
                            <a href="/locations/{{ $company->locations->first()->hashed_id }}/sources/create" class="btn btn-secondary waves-effect text-left text-light">Connect Your Accounts</a>
                        @endif
                    </div>

                @endif
            </div>
        </div>
        <div class="col-md-3">
            <div class="card-box">
                <h4 class="m-t-0 m-b-30 header-title">Perception Map</h4>

                <canvas id="myChart" width="400" height="400"></canvas>
            </div>
        </div>
    </div>
        <!-- <div class="col-md-3">
            <div class="card-box">
                <div id="bubble-graph"></div>
            </div>

            <div class="card-box">
                <h4 class="m-t-0 m-b-30 header-title">Perception Map</h4>

                <canvas id="myChart" width="400" height="400"></canvas>
            </div>
        </div> -->

@endsection

@push('scripts')
    <script src="/plugins/chartist/dist/chartist.min.js"></script>
    <script src="/plugins/chartist-plugin-tooltips/dist/chartist-plugin-tooltip.js"></script>

    <script>
        $(function(){
            var ctx = document.getElementById("myChart").getContext('2d');
            var myChart = new Chart(ctx, {
                type: 'radar',
                data: {
                    labels: {!! json_encode($categories->map(function($c){ return $c->text; })) !!},
                    datasets: [{
                        label: "Your Score",
                        data: [
                            @foreach ($categories as $category)
                                {{ $reviews->sum(strtolower($category->text)) / max($reviews->count(), 1) }},
                            @endforeach
                        ],
                        backgroundColor: [
                            'rgba(255, 99, 132, 0.2)'
                        ],
                        borderWidth: 1
                    },
                    // {
                    //     label: "Competition Score",
                    //     data: [
                    //         @foreach ($categories as $category)
                    //             0.25,
                    //         @endforeach
                    //     ],
                    //     backgroundColor: [
                    //         'rgba(54, 162, 235, 0.2)'
                    //     ],
                    //     borderWidth: 1
                    // }
                    ]
                },
                options: {

                }
            });

            @if ($sourceIds->count() > 0)
                new Chartist.Line('#line-graph', {
                    labels: [
                        @foreach ($perSourcePerDay[$sourceIds[0]] as $d => $c)
                            @if(strtotime($d) <= 86400)
                                @for($i = 4; $i > 0; $i--)
                                    '{{ date('m/d/y', strtotime($d) - $i * 86400) }}',
                                @endfor
                            @endif
                            '{{ $d }}',
                        @endforeach
                    ],
                    series: [
                        @foreach ($perSourcePerDay as $s => $dCounts)
                            [
                                @foreach ($dCounts as $d => $counts)
                                    @if(strtotime($d) <= 86400)
                                        @for($i = 0; $i < 5; $i++)
                                            {{ $counts->sum('count') ?? 0 }},
                                        @endfor
                                    @else
                                        {meta: '{{( $counts[0]->source->text ?? "" )}}', value: '{{ $counts->sum('count') ?? 0 }}'},
                                    @endif
                                @endforeach
                            ],
                        @endforeach
                    ],
                },
                {
                    // high: 3,
                    // low: -3,
                    showArea: true,
                        showLine: false,
                    showPoint: true,
                    fullWidth: true,
                    chartPadding: {
                        right: 50
                    },
                    axisX: {
                    showLabel: true,
                        showGrid: false
                },
                    plugins: [
                        Chartist.plugins.tooltip({

                        })
                    ]
                });
            @endif
        });


        (function() {

          // Fake JSON data
          var json = {"countries_msg_vol": {
            "CA": 170, "US": 393, "BB": 120
          }};

            // D3 Bubble Chart

            var diameter = 300;

            var svg = d3.select('#bubble-graph').append('svg')
                            .attr('width', diameter)
                            .attr('height', diameter);

            var bubble = d3.layout.pack()
                        .size([diameter, diameter])
                        .value(function(d) {return d.size;})
                 // .sort(function(a, b) {
                        //  return -(a.value - b.value)
                        // })
                        .padding(4);

          // generate data with calculated layout values
          var nodes = bubble.nodes(processData(json))
                                .filter(function(d) { return !d.children; }); // filter out the outer bubble

          var vis = svg.selectAll('circle')
                            .data(nodes);

          vis.enter().append('circle')
                    .attr('transform', function(d) { return 'translate(' + d.x + ',' + d.y + ')'; })
                    .attr('r', function(d) { return d.r; })
                    .attr('class', function(d) { return d.className; });

          function processData(data) {
            var obj = data.countries_msg_vol;

            var newDataSet = [];

            for(var prop in obj) {
              newDataSet.push({name: prop, className: prop.toLowerCase(), size: obj[prop]});
            }
            return {children: newDataSet};
          }

        })();
    </script>
@endpush