routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::auth();

Route::get('/cron/reviews', 'CronController@getReviews');
Route::get('/cron/rate_reviews', 'CronController@rateReviews');
Route::get('/cron/daily', 'CronController@daily');

// Kiosk Mode
Route::get('/locations/{location}/reviewer', 'ReviewerController@createForLocation');
Route::post('/locations/{location}/reviewer', 'ReviewerController@storeForLocation');
Route::get('/locations/{location}/reviewer/success/{reviewer}', 'ReviewerController@successForLocation');
Route::get('/locations/{location}/write/{reviewer}', 'WriteReviewController@index');
Route::post('/locations/{location}/write/{reviewer}', 'WriteReviewController@store');
Route::get('/reviewer/{reviewer}/unsubscribe', 'ReviewerController@unsubscribe');

Route::get('/sms', 'CommunicationController@sms');

//for iframe
Route::get('/reviews/{location}/{user}', 'ReviewController@getLocationReviews')->name('getLocationReviews');

Route::group(['middleware' => 'auth'], function () {
	Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout');

    Route::post('/insights/search-competitors', 'InsightController@search');
    Route::post('/insights/save-competitor', 'InsightController@saveCompetitor');
    Route::get('/insights/competitors/{location}', 'InsightController@competitors')->name('competitors');
	Route::resource('/insights', 'InsightController');

	Route::get('/users/{user}/login', 'UserManagementController@supervise');
    Route::get('/users/create', 'UserManagementController@create')->name('users.create');
    Route::resource('/users', 'UserManagementController', ['except' => 'create']);

    Route::get('/team-members/{company}', 'TeamMemberController@index')->name('team-members.index');
    Route::get('/team-members/create/{company?}', 'TeamMemberController@create')->name('team-members.create');
    Route::get('/team-members/{companyUser}/edit', 'TeamMemberController@edit')->name('team-members.edit');
    Route::post('/team-members/{companyUser}', 'TeamMemberController@update')->name('team-members.update');
    Route::resource('/team-members', 'TeamMemberController', ['except' => 'index', 'create', 'edit', 'update']);

    //Route::resource('/permissions', 'PermissionController', ['only' => ['edit', 'update']]);
    Route::get('/permissions/{user}', 'PermissionController@edit')->name('permissions-edit');
    Route::post('/permissions/{user}', 'PermissionController@edit')->name('permissions-update');

	// Dashboard
	Route::get('/dashboard/location/{location}', 'DashboardController@setActiveLocation');
	Route::resource('/', 'DashboardController');
	Route::group(['middleware' => 'admin'], function () {
        Route::get('/super-dashboard', 'SuperDashboardController@index');
    });

    // Reviews
    Route::get('/reviews/reviews', 'ReviewController@getReviews');
	Route::post('/reviews/{review}/star', 'ReviewController@toggleStarred');

	Route::get('/reviews/{review}/{read}', 'ReviewController@show');
	Route::resource('/reviews', 'ReviewController');

	// Locations
    Route::get('/locations/{location}/reviews-widget', 'LocationController@reviewsWidget')->name('reviews-widget');
    //Route::put('/locations/{location}')
    Route::resource('/locations', 'LocationController');

    // Settings
	Route::get('/settings/primaryCard/{card}', 'SettingController@primaryCard');
	Route::post('/settings/saveCard', 'SettingController@saveCard');
	Route::resource('/settings', 'SettingController');

	// Reviews
	Route::get('/reviewers/import', 'ReviewerController@showImport');
	Route::get('/reviewers/{reviewer}/textForReview', 'ReviewerController@textForReview');
	Route::get('/reviewers/{reviewer}/emailForReview', 'ReviewerController@emailForReview');
	Route::get('/reviewers/{reviewer}/newCommunication', 'ReviewerController@newCommunication');
	Route::post('/reviewers/{reviewer}/communication', 'ReviewerController@sendCommunication');
	Route::post('/reviewers/import', 'ReviewerController@import');
	Route::resource('/reviewers', 'ReviewerController');

	// Sentiments
	Route::post('/sentiments/{category}/words', 'SentimentController@addWord');
	Route::put('/sentiments/{category}/words/{word}', 'SentimentController@editWord');
	Route::get('/sentiments/{category}/words/{word}/remove', 'SentimentController@deleteWord');
	Route::get('/sentiments/run', 'SentimentController@run');
	Route::resource('/sentiments', 'SentimentController');

	// Onboarding
	Route::get('/onboarding/search', 'OnboardingController@businessSearch');
	Route::get('/onboarding/coupon_lookup', 'OnboardingController@checkCoupon');
	Route::get('/onboarding/{step}', 'OnboardingController@showStep');
	Route::post('/onboarding/1', 'OnboardingController@saveInfo');
	Route::post('/onboarding/2', 'OnboardingController@addSource');
	Route::post('/onboarding/3', 'OnboardingController@saveCard');
	Route::post('/onboarding/4', 'OnboardingController@termsAccepted');
		
	// Sources
	Route::get('/locations/{location}/sources/fbpages', 'SourceController@getFbPages');
	Route::get('/locations/{location}/sources/googpages', 'SourceController@getGoogPages');
	Route::get('/locations/{location}/sources/yelpplaces', 'SourceController@getYelpPlaces');
	Route::get('/locations/{location}/sources/{source}/delete', 'SourceController@destory');
	Route::get('/oauth/googleredirect', 'SourceController@googleOauth');
    Route::post('/locations/store-media', 'LocationController@storeMedia');
    Route::resource('/locations/{location}/sources', 'SourceController');

    // Contact
    Route::post('/contact', 'ContactController@submit')->name('contact');

    //Notifications
    Route::get('/notifications', 'NotificationController@index')->name('notifications');

    //Potential leads
    Route::put('/leads/confirm', 'LeadController@confirm')->name('leads.confirm');
    Route::get('/leads/import', 'LeadController@import')->name('leads.import');
    Route::post('/leads/upload', 'LeadController@upload')->name('leads.upload');
    Route::get('/leads/check/{lead}', 'LeadController@check')->name('leads.check');
    Route::get('leads/{lead}/edit/{check?}', 'LeadController@edit')->name('leads.edit');
    Route::put('/leads/{lead}/{check?}', 'LeadController@update')->name('leads.update');
    Route::resource('/leads', 'LeadController', ['except' => ['edit', 'update']]);
    //Route::resource('/leads', 'LeadController');

    // Testing :)
    Route::get('/tests/getGoogle', 'TestController@getGoogle');
    Route::get('/tests/getFb', 'TestController@getFbReviews');

});

app/Models/Lead.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Lead extends Model
{
    public $timestamps = false;
    protected $guarded = [];

}

app/Http/Controllers/LeadController.php
<?php

namespace App\Http\Controllers;

use App\Adapter\LocationAdapter;
use App\Http\Requests\StoreLeads;
use App\Http\Requests\UploadLeads;
use App\Models\Lead;
use App\Models\User;
use App\Services\Locations\FindGooglePlaceService;
use App\Services\Locations\FindYelpPlaceService;
use App\Services\Locations\YelpClientService;
use App\Services\ParseFacebook;
use GooglePlaces;
use Illuminate\Http\Request;
use Maatwebsite\Excel\Facades\Excel;
use SKAgarwal\GoogleApi\Exceptions\GooglePlacesApiException;

class LeadController extends Controller
{
    private $googlePlaceService;
    public $fb_service;
    private $locationAdapter;

    public function __construct(
        FindGooglePlaceService $googlePlaceService,
        ParseFacebook $parseFacebook,
        LocationAdapter $locationAdapter
    )
    {
        $this->googlePlaceService = $googlePlaceService;
        $this->fb_service = $parseFacebook;
        $this->locationAdapter = $locationAdapter;
    }

    public function index()
    {
        $leads = Lead::orderBy('id', 'DESC')->paginate(20);
        return view('leads.index')->with([
            'leads' => $leads,
        ]);
    }

    public function create()
    {
        return view('leads.create');
    }

    public function store(StoreLeads $request)
    {
        try {
            $lead = Lead::create($request->input());
        } catch (\Exception $e) {
            \Log::error($e->getMessage());
            return redirect()->back()->withErrors(['Something went wrong']);
        }
        return redirect()->route('leads.check', ['lead' => $lead])->withSuccess('New lead was added!');
    }

    public function import()
    {
        return view('leads.import');
    }

    public function upload(UploadLeads $request)
    {
        $path = $request->file('file')->getRealPath();
        $data = Excel::load($path, function($reader) {})->get()->toArray();

        if (count($data) > 0) {
            foreach ($data as $row) {
                try {
                    $user = User::where(['email' => $row['email']])->first();
                    if(!$user) {
                        Lead::create([
                            'name' => $row['name'],
                            'email' => $row['email'],
                            'company_name' => $row['company_name'],
                            'address_1' => $row['shipping_address_1'],
                            'address_2' => $row['shipping_address_2'],
                            'city' => $row['shipping_city'],
                            'state' => $row['shipping_stateprovince'],
                            'zip' => $row['shipping_zip'],
                        ]);
                    } else {
                        continue;
                    }

                } catch (\Exception $e) {
                    \Log::error($e->getMessage());
                }
            }
        } else {
            return redirect()->back()->withErrors(['File is empty!']);
        }

        return redirect()->route('leads.index')->withSuccess('Leads were successfully imported!');
    }

    public function show(Lead $lead)
    {
        return view('leads.show')->with([
            'lead' => $lead
        ]);
    }

    public function edit(Lead $lead, $check = false)
    {
        return view('leads.edit')->with([
            'lead' => $lead,
            'check' => $check,
        ]);
    }

    public function update(StoreLeads $request, Lead $lead, $check = false)
    {
        try {
            Lead::where('id', $lead->id)->update($request->except('_method', '_token'));
        } catch (\Exception $e) {
            \Log::error($e->getMessage());
            return redirect()->back()->withErrors(['Something went wrong']);
        }
        if(!$check) {
            return redirect()->route('leads.index')->withSuccess('Lead was updated!');
        } else {
            return redirect()->route('leads.check', ['lead' => $lead])->withSuccess('Lead was updated!');
        }
    }

    public function check(Lead $lead)
    {
        if($lead->google_place_id) {
            $place = $this->googlePlaceService->findById($lead->google_place_id);
        } else {
           $place = $this->googlePlaceService->find($this->locationAdapter->adaptLead($lead));
        }

        return view('leads.check')->with([
            'lead' => $lead,
            'place' => $place,
        ]);
    }

    public function confirm(Request $request)
    {
        try {
            Lead::where('id', $request->lead_id)->update([
                'address_1' => $request->full_address,
                'company_name' => $request->name,
                'google_rating' => $request->google_rating,
                'google_place_id' => $request->google_place_id,
                'yelp_id' => FindYelpPlaceService::getBusinessId($request),
                'fb_id' => $this->fb_service->getPlaceId($request),
                'checked' => 1,
            ]);
        } catch (\Exception $e) {
            \Log::error($e->getMessage());
            return redirect()->back()->withErrors(['Something went wrong']);
        }

        return redirect()->route('leads.index')->withSuccess('Location was confirmed!');
    }
}

resources/views/leads/check.blade.php
@extends('layouts.dashboard')

@section('title')
    Information check
@endsection

@section('content')
    <div class="row">
        <div class="col-12">
            <div class="card-box">
                <h4 class="text-dark  header-title m-t-0">Information check</h4>
                <br>

                <div class="row">
                    <div class="col-6">
                        <h2>Imported data</h2>
                        <p class="{{ $lead->salutation ? '' : 'text-danger' }}">
                            <b>Salutation:</b> {{ $lead->salutation ?? 'Missing' }}
                        </p>
                        <p class="{{ $lead->name ? '' : 'text-danger' }}">
                            <b>Name:</b> {{ $lead->name ?? 'Missing'  }}
                        </p>
                        <p class="{{ $lead->company_name ? '' : 'text-danger' }}">
                            <b>Company name:</b> {{ $lead->company_name ?? 'Missing' }}
                        </p>
                        <p class="{{ $lead->email ? '' : 'text-danger' }}">
                            <b>Email:</b> {{ $lead->email }}
                        </p>
                        <p class="{{ $lead->address_1 ? '' : 'text-danger' }}">
                            <b>Address 1:</b> {{ $lead->address_1 ?? 'Missing' }}
                        </p>
                        <p class="{{ $lead->address_2 ? '' : 'text-danger' }}">
                            <b>Address 2:</b> {{ $lead->address_2 ?? 'Missing' }}
                        </p>
                        <p class="{{ $lead->place_type ? '' : 'text-danger' }}">
                            <b>Place Type:</b> {{ $lead->place_type ?? 'Missing' }}
                        </p>
                        <p class="{{ $lead->city ? '' : 'text-danger' }}">
                            <b>City:</b> {{ $lead->city ?? 'Missing' }}
                        </p>
                        <p class="{{ $lead->state ? '' : 'text-danger' }}">
                            <b>State:</b> {{ $lead->state ?? 'Missing' }}
                        </p>
                        <p class="{{ $lead->country ? '' : 'text-danger' }}">
                            <b>Country:</b> {{ $lead->country ?? 'Missing' }}
                        </p>
                        <p class="{{ $lead->zip ? '' : 'text-danger' }}">
                            <b>Zip:</b> {{ $lead->zip ?? 'Missing' }}
                        </p>
                        <p class="{{ $lead->phone ? '' : 'text-danger' }}">
                            <b>Phone:</b> {{ $lead->phone ?? 'Missing' }}
                        </p>

                        <a href="{{ route('leads.edit', ['lead' => $lead, 'check' => 1]) }}" class="btn btn-success btn-sm">
                            <span class="fa fa-pencil"></span>
                            Edit
                        </a>
                    </div>
                    <div class="col-6 text-center">
                        <h2>Matched location</h2>
                        @isset($place)
                            @if($place === 0)
                                <div class="alert alert-danger">
                                    <strong>
                                        Location not found!
                                    </strong>
                                    Try to add more company information or search manually.
                                </div>
                            @else
                                <div class="card-box widget-bg-color-icon">
                                    <div class="place-icon-div">
                                        @isset($place['icon'])
                                            <img id="place_icon" src="{{ $place['icon'] }}" alt="{{ $place['name'] }}" >
                                        @else
                                            <i class="mdi mdi-home-modern" style="margin-top: 14px; font-size: 53px; color: #999"></i>
                                        @endif
                                    </div>

                                    <h2 id="place_name" style="text-align: center; margin-top: 5px;"> {{ $place['name'] }} </h2>
                                    <p id="place_address" class="text-center"> {{ $place['formatted_address'] }} </p>

                                    @isset($place['rating'])
                                        <p id="place_rating" class="text-center" style="font-size: 30px;">
                                            @for($i = 0; $i < round($place['rating'], 0); $i++)
                                                <i class="mdi mdi-star" style="color: gold"></i>
                                            @endfor

                                            @for($i = 0; $i < 5 - round($place['rating'], 0); $i++)
                                                <i class="mdi mdi-star" style="color: grey"></i>
                                            @endfor
                                        </p>
                                    @else
                                        <p id="place_rating" class="text-center" style="font-size: 30px;">
                                            @for($i = 0; $i < 5; $i++)
                                                <i class="mdi mdi-star" style="color: grey"></i>
                                            @endfor
                                        </p>
                                    @endif

                                    <div class="text-center">
                                        Found on <i class="fa fa-google"></i>
                                    </div>
                                </div>

                                <a href="javascript:void(0)" id="change_location" class="btn btn-success btn-sm"><i class="fa fa-search"></i> Find another location</a>

                                <div id="location-name-container" class="col-12">
                                    <div class="form-group clearfix row m-t-10">
                                        <label class="col-3 col-form-label" for="location_name">Location Name</label>
                                        <div class="hidden col-9" id="location_text">
                                            <input class="form-control required" name="location_name" type="text" value="{{ old('text') }}">
                                        </div>
                                        <select class="form-control select2 change-location col-9 " name='yelp_id'></select>
                                    </div>
                                </div>

                                <form role="form" action="{{ route('leads.confirm') }}" method="post" id="change_location_form">
                                    <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                    <input type="hidden" name="_method" value="PUT">
                                    <input type="hidden" name='lead_id' value="{{ $lead->id }}">
                                    <input type="hidden" name='name' value="{{ isset($place['name']) ? $place['name'] : null }}">
                                    <input type="hidden" name='full_address' value="{{ isset($place['formatted_address']) ? $place['formatted_address'] : null }}">
                                    <input type="hidden" name="icon" value="{{ isset($place['icon']) ? $place['icon'] : null}}">
                                    <input type="hidden" name="google_rating" value="{{ isset($place['rating']) ? $place['rating'] : null }}">
                                    <input type="hidden" name="google_place_id" value="{{ isset($place['place_id']) ? $place['place_id'] : null }}">
                                    <input type="hidden" name="lead" value="{{ $lead }}">
                                </form>
                            @endif
                        @else
                            <div class="alert alert-danger">
                                <strong>
                                    Too few information to find a location.
                                </strong>
                                Please, add more company information.
                            </div>
                        @endif
                    </div>
                    @isset($place)
                        <div class="col-12 text-center">
                            <button type="submit" class="btn btn-primary" id="confirm_button">Confirm!</button>
                        </div>
                    @else
                        <div class="col-12 text-center">
                            <button type="submit" class="btn btn-primary" id="confirm_button" disabled style="cursor: not-allowed;">Confirm!</button>
                        </div>
                    @endif
                </div>
            </div>
        </div>
    </div>
    <!-- end row -->
@endsection

@push('scripts')
    <script src="{{ asset('js/change_location.js') }}"></script>
@endpush

resources/views/leads/create.blade.php
@extends('layouts.dashboard')

@section('title')
    Potential Leads
@endsection

@section('content')
    <div class="row">
        <div class="col-12">
            <div class="card-box">
                <h4 class="text-dark  header-title m-t-0">Create Leads</h4>
                <br>

                <form action="{{ route('leads.store') }}" method="post">
                    {{ csrf_field() }}

                    <div class="form-group row">
                        <label class="col-2 col-form-label">Salutation</label>
                        <div class="col-10">
                            <input name="salutation" type="text" class="form-control" value=" {{ old('salutation') }}">
                        </div>
                    </div>

                    <div class="form-group row">
                        <label class="col-2 col-form-label">Full Name</label>
                        <div class="col-10">
                            <input name="name" type="text" class="form-control" value="{{ old('name') }}">
                        </div>
                    </div>

                    <div class="form-group row">
                        <label class="col-2 col-form-label">Company Name</label>
                        <div class="col-10">
                            <input name="company_name" type="text" class="form-control" value="{{ old('company_name') }}">
                        </div>
                    </div>

                    <div class="form-group row">
                        <label class="col-2 col-form-label">Email</label>
                        <div class="col-10">
                            <input name="email" type="email" class="form-control" value="{{ old('email') }}">
                        </div>
                    </div>

                    <div class="form-group row">
                        <label class="col-2 col-form-label">Address 1</label>
                        <div class="col-10">
                            <input name="address_1" type="text" class="form-control" value="{{ old('address_1') }}">
                        </div>
                    </div>

                    <div class="form-group row">
                        <label class="col-2 col-form-label">Address 2</label>
                        <div class="col-10">
                            <input name="address_2" type="text" class="form-control" value="{{ old('address_2') }}">
                        </div>
                    </div>

                    <div class="form-group row">
                        <label class="col-2 col-form-label">City</label>
                        <div class="col-10">
                            <input name="city" type="text" class="form-control" value="{{ old('city') }}">
                        </div>
                    </div>

                    <div class="form-group row">
                        <label class="col-2 col-form-label">State</label>
                        <div class="col-10">
                            <input name="state" type="text" class="form-control" value="{{ old('state') }}">
                        </div>
                    </div>

                    <div class="form-group row">
                        <label class="col-2 col-form-label">Country</label>
                        <div class="col-10">
                            <input name="country" type="text" class="form-control" value="{{ old('country') ?? 'US' }}">
                        </div>
                    </div>

                    <div class="form-group row">
                        <label class="col-2 col-form-label">Zip</label>
                        <div class="col-10">
                            <input name="zip" type="text" class="form-control" value="{{ old('zip') }}">
                        </div>
                    </div>

                    <div class="form-group row">
                        <label class="col-2 col-form-label">Phone</label>
                        <div class="col-10">
                            <input name="phone" type="tel" class="form-control" value="{{ old('phone') }}">
                        </div>
                    </div>

                    <div class="form-group row">
                        <label class="col-2 col-form-label">Type of place</label>
                        <div class="col-10">
                            <input name="place_type" type="text" class="form-control" value="{{ old('place_type') }}">
                        </div>
                    </div>

                    <button type="submit" class="btn btn-primary mb-2">Save</button>
                </form>

            </div>
        </div>
    </div>
    <!-- end row -->
@endsection

resources/views/leads/edit.blade.php
@extends('layouts.dashboard')

@section('title')
    Potential Leads
@endsection

@section('content')
    <div class="row">
        <div class="col-12">
            <div class="card-box">
                <h4 class="text-dark  header-title m-t-0">Edit Lead {{ $lead->salutation }} {{ $lead->first_name }} {{ $lead->last_name }}</h4>
                <br>

                <form action="{{ route('leads.update', ['lead' => $lead, 'check' => $check]) }}" method="post">
                    <input type="hidden" name="_method" value="PUT">
                    {{ csrf_field() }}

                    <div class="form-group row">
                        <label class="col-2 col-form-label">Salutation</label>
                        <div class="col-10">
                            <input name="salutation" type="text" class="form-control" value=" {{ $lead->salutation }}">
                        </div>
                    </div>

                    <div class="form-group row">
                        <label class="col-2 col-form-label">Name</label>
                        <div class="col-10">
                            <input name="name" type="text" class="form-control" value="{{ $lead->name }}">
                        </div>
                    </div>

                    <div class="form-group row">
                        <label class="col-2 col-form-label">Company Name</label>
                        <div class="col-10">
                            <input name="company_name" type="text" class="form-control" value="{{ $lead->company_name }}">
                        </div>
                    </div>

                    <div class="form-group row">
                        <label class="col-2 col-form-label">Email</label>
                        <div class="col-10">
                            <input name="email" type="email" class="form-control" value="{{ $lead->email }}">
                        </div>
                    </div>

                    <div class="form-group row">
                        <label class="col-2 col-form-label">Address 1</label>
                        <div class="col-10">
                            <input name="address_1" type="text" class="form-control" value="{{ $lead->address_1}}">
                        </div>
                    </div>

                    <div class="form-group row">
                        <label class="col-2 col-form-label">Address 2</label>
                        <div class="col-10">
                            <input name="address_2" type="text" class="form-control" value="{{ $lead->address_2 }}">
                        </div>
                    </div>

                    <div class="form-group row">
                        <label class="col-2 col-form-label">City</label>
                        <div class="col-10">
                            <input name="city" type="text" class="form-control" value="{{ $lead->city }}">
                        </div>
                    </div>

                    <div class="form-group row">
                        <label class="col-2 col-form-label">State</label>
                        <div class="col-10">
                            <input name="state" type="text" class="form-control" value="{{ $lead->state }}">
                        </div>
                    </div>

                    <div class="form-group row">
                        <label class="col-2 col-form-label">Country</label>
                        <div class="col-10">
                            <input name="state" type="text" class="form-control" value="{{ $lead->country }}">
                        </div>
                    </div>

                    <div class="form-group row">
                        <label class="col-2 col-form-label">Zip</label>
                        <div class="col-10">
                            <input name="zip" type="text" class="form-control" value="{{ $lead->zip }}">
                        </div>
                    </div>

                    <div class="form-group row">
                        <label class="col-2 col-form-label">Phone</label>
                        <div class="col-10">
                            <input name="phone" type="tel" class="form-control" value="{{ $lead->phone }}">
                        </div>
                    </div>

                    <div class="form-group row">
                        <label class="col-2 col-form-label">Type of place</label>
                        <div class="col-10">
                            <input name="place_type" type="text" class="form-control" value="{{ $lead->place_type }}">
                        </div>
                    </div>

                    <button type="submit" class="btn btn-primary mb-2">Save</button>
                </form>

            </div>
        </div>
    </div>
    <!-- end row -->
@endsection