routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::auth();

Route::get('/cron/reviews', 'CronController@getReviews');
Route::get('/cron/rate_reviews', 'CronController@rateReviews');
Route::get('/cron/daily', 'CronController@daily');

// Kiosk Mode
Route::get('/locations/{location}/reviewer', 'ReviewerController@createForLocation');
Route::post('/locations/{location}/reviewer', 'ReviewerController@storeForLocation');
Route::get('/locations/{location}/reviewer/success/{reviewer}', 'ReviewerController@successForLocation');
Route::get('/locations/{location}/write/{reviewer}', 'WriteReviewController@index');
Route::post('/locations/{location}/write/{reviewer}', 'WriteReviewController@store');
Route::get('/reviewer/{reviewer}/unsubscribe', 'ReviewerController@unsubscribe');

Route::get('/sms', 'CommunicationController@sms');

//for iframe
Route::get('/reviews/{location}/{user}', 'ReviewController@getLocationReviews')->name('getLocationReviews');

Route::group(['middleware' => 'auth'], function () {
	Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout');

    Route::post('/insights/search-competitors', 'InsightController@search');
    Route::post('/insights/save-competitor', 'InsightController@saveCompetitor');
    Route::get('/insights/competitors/{location}', 'InsightController@competitors')->name('competitors');
	Route::resource('/insights', 'InsightController');

	Route::get('/users/{user}/login', 'UserManagementController@supervise');
    Route::get('/users/create', 'UserManagementController@create')->name('users.create');
    Route::resource('/users', 'UserManagementController', ['except' => 'create']);

    Route::get('/team-members/{company}', 'TeamMemberController@index')->name('team-members.index');
    Route::get('/team-members/create/{company?}', 'TeamMemberController@create')->name('team-members.create');
    Route::get('/team-members/{companyUser}/edit', 'TeamMemberController@edit')->name('team-members.edit');
    Route::post('/team-members/{companyUser}', 'TeamMemberController@update')->name('team-members.update');
    Route::resource('/team-members', 'TeamMemberController', ['except' => 'index', 'create', 'edit', 'update']);

    //Route::resource('/permissions', 'PermissionController', ['only' => ['edit', 'update']]);
    Route::get('/permissions/{user}', 'PermissionController@edit')->name('permissions-edit');
    Route::post('/permissions/{user}', 'PermissionController@edit')->name('permissions-update');

	// Dashboard
	Route::get('/dashboard/location/{location}', 'DashboardController@setActiveLocation');
	Route::resource('/', 'DashboardController');
	Route::group(['middleware' => 'admin'], function () {
        Route::get('/super-dashboard', 'SuperDashboardController@index');
    });

    // Reviews
    Route::get('/reviews/reviews', 'ReviewController@getReviews');
	Route::post('/reviews/{review}/star', 'ReviewController@toggleStarred');

	Route::get('/reviews/{review}/{read}', 'ReviewController@show');
	Route::resource('/reviews', 'ReviewController');

	// Locations
    Route::get('/locations/{location}/reviews-widget', 'LocationController@reviewsWidget')->name('reviews-widget');
    //Route::put('/locations/{location}')
    Route::resource('/locations', 'LocationController');

    // Settings
	Route::get('/settings/primaryCard/{card}', 'SettingController@primaryCard');
	Route::post('/settings/saveCard', 'SettingController@saveCard');
	Route::resource('/settings', 'SettingController');

	// Reviews
	Route::get('/reviewers/import', 'ReviewerController@showImport');
	Route::get('/reviewers/{reviewer}/textForReview', 'ReviewerController@textForReview');
	Route::get('/reviewers/{reviewer}/emailForReview', 'ReviewerController@emailForReview');
	Route::get('/reviewers/{reviewer}/newCommunication', 'ReviewerController@newCommunication');
	Route::post('/reviewers/{reviewer}/communication', 'ReviewerController@sendCommunication');
	Route::post('/reviewers/import', 'ReviewerController@import');
	Route::resource('/reviewers', 'ReviewerController');

	// Sentiments
	Route::post('/sentiments/{category}/words', 'SentimentController@addWord');
	Route::put('/sentiments/{category}/words/{word}', 'SentimentController@editWord');
	Route::get('/sentiments/{category}/words/{word}/remove', 'SentimentController@deleteWord');
	Route::get('/sentiments/run', 'SentimentController@run');
	Route::resource('/sentiments', 'SentimentController');

	// Onboarding
	Route::get('/onboarding/search', 'OnboardingController@businessSearch');
	Route::get('/onboarding/coupon_lookup', 'OnboardingController@checkCoupon');
	Route::get('/onboarding/{step}', 'OnboardingController@showStep');
	Route::post('/onboarding/1', 'OnboardingController@saveInfo');
	Route::post('/onboarding/2', 'OnboardingController@addSource');
	Route::post('/onboarding/3', 'OnboardingController@saveCard');
	Route::post('/onboarding/4', 'OnboardingController@termsAccepted');
		
	// Sources
	Route::get('/locations/{location}/sources/fbpages', 'SourceController@getFbPages');
	Route::get('/locations/{location}/sources/googpages', 'SourceController@getGoogPages');
	Route::get('/locations/{location}/sources/yelpplaces', 'SourceController@getYelpPlaces');
	Route::get('/locations/{location}/sources/{source}/delete', 'SourceController@destory');
	Route::get('/oauth/googleredirect', 'SourceController@googleOauth');
    Route::post('/locations/store-media', 'LocationController@storeMedia');
    Route::resource('/locations/{location}/sources', 'SourceController');

    // Contact
    Route::post('/contact', 'ContactController@submit')->name('contact');

    //Notifications
    Route::get('/notifications', 'NotificationController@index')->name('notifications');

    //Potential leads
    Route::put('/leads/confirm', 'LeadController@confirm')->name('leads.confirm');
    Route::get('/leads/import', 'LeadController@import')->name('leads.import');
    Route::post('/leads/upload', 'LeadController@upload')->name('leads.upload');
    Route::get('/leads/check/{lead}', 'LeadController@check')->name('leads.check');
    Route::get('leads/{lead}/edit/{check?}', 'LeadController@edit')->name('leads.edit');
    Route::put('/leads/{lead}/{check?}', 'LeadController@update')->name('leads.update');
    Route::resource('/leads', 'LeadController', ['except' => ['edit', 'update']]);
    //Route::resource('/leads', 'LeadController');

    // Testing :)
    Route::get('/tests/getGoogle', 'TestController@getGoogle');
    Route::get('/tests/getFb', 'TestController@getFbReviews');

});

resources/views/user-managment/create.blade.php
@extends('layouts.dashboard')

@section('title')
    @isset($company)
        Add Team Member for {{ $company->text }}
    @else
        Add User
    @endisset
@endsection

@section('content')
    <div class="row">
    	<div class="col-lg-9 col-md-12">
	    	<div class="card-box">
	        	<form class="form-horizontal" role="form" action="{{ $company ? route('team-members.store') : action('UserManagementController@store') }}" method="post">
	        		<input type="hidden" name="_token" value="{{ csrf_token() }}">
					@isset($company)
	        			<input type="hidden" name="company" value="{{ $company->id }}">
					@endisset

			        <div class="form-group row">
			            <label for="member-name" class="col-3 col-form-label">Name</label>
			            <div class="col-9">
								<input class="form-control" id="member-name" name='name' value='{{ old('name') }}'>
						</div>
			        </div>

			        <div class="form-group row">
			            <label for="member-email" class="col-3 col-form-label">Email</label>
			            <div class="col-9">
			                <input class="form-control" id="member-email" type="email" name='email' value='{{ old('email') }}'>
			            </div>
			        </div>

			        <div class="form-group row">
			            <label for="member-title" class="col-3 col-form-label">Title</label>
			            <div class="col-9">
			                <input class="form-control" id="member-title" name='title' value='{{ old('title') }}'>
			            </div>
			        </div>

			        <div class="form-group m-b-0 row">
			            <div class="offset-3 col-9">
			                <button type="submit" class="btn btn-success">Add</button>
			            </div>
			        </div>

			    </form>
			</div>
		</div>
    </div>
    <!-- end row -->

@endsection

resources/views/user-managment/index.blade.php
@extends('layouts.dashboard')

@section('title')
    Template
@endsection

@section('content')
    <div class="row">
        <div class="col-lg-12">
            <div class="card-box">
                <h4 class="text-dark  header-title m-t-0">All Users
                	<div class="pull-right">
                		<a href="{{ route('users.create') }}" class="pull-right btn btn-success btn-sm" id="btn-archive">Add User</a>
                	</div>
                </h4>
                <br>

                <table class="table mb-0 table-responsive">
                    <thead>
	                    <tr>
	                        <th>#</th>
	                        <th>Name</th>
	                        <th>Email</th>
	                        <th>Role</th>
	                        <th></th>
	                    </tr>
                    </thead>
                    <tbody>
                    	@foreach($users as $user)
		                    <tr>
		                        <td>{{ $user->id }}</td>
		                        <td>{{ $user->name }}</td>
		                        <td>{{ $user->email }}</td>
		                        <td>{{ $user->role_id }}</td>
		                        <td>
		                        	<a href="/users/{{ $user->id }}/login" class="btn btn-primary">
		                        		<i class="fa fa-blind"></i>
		                        	</a>
								</td>
		                    </tr>
		                @endforeach

                    </tbody>
                </table>
            </div>
        </div>
    </div>

@endsection

@push('scripts')

@endpush